# Generated by Django 4.0.5 on 2022-07-24 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('book_name', models.CharField(blank=True, max_length=255)),
                ('book_price', models.FloatField(blank=True)),
                ('book_des', models.CharField(blank=True, max_length=2000)),
                ('book_stock', models.CharField(blank=True, max_length=255)),
                ('prod_cat', models.CharField(blank=True, max_length=255)),
                ('book_image', models.FileField(default='default.jpg', upload_to='static/images')),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
